# Specify The Base Image
FROM node:alpine

# Provide Maintainer Information
MAINTAINER MohammadHosein Chahardoli <mohammadhoseinchahardoli@gmail.com>

# Specify Working Directory
WORKDIR /app

# Add package.json
COPY ./package.json .

# Download and Install All The Dependencies
RUN ["npm", "install"]
RUN npm install --save-dev @testing-library/jest-dom

# Add The Application Source Code
COPY ./ ./

# Run The Application
CMD ["npm", "run", "start"]
