---
version: '3'
services:
  postgres:
    image: library/postgres:latest
    environment:
      - POSTGRES_PASSWORD=fibonaccipassword

  redis:
    image: library/redis:latest
    command:
      - --loglevel warning

  backend:
    image: chahardoli/fibo-backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=fibonaccipassword
    depends_on:
      - postgres
      - redis

  worker:
    image: chahardoli/fibo-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
      - backend

  frontend:
    image: chahardoli/fibo-frontend
    depends_on:
      - postgres
      - redis
      - backend
      - worker
    stdin_open: true

  nginx:
    image: chahardoli/fibo-nginx
    depends_on:
      - backend
      - worker
      - frontend
      - redis
      - postgres
    ports:
    - 80:80
