# Specify The Base Image
FROM nginx:latest

# Provide Maintainer Information
MAINTAINER MohammadHosein Chahardoli <mohammadhoseinchahardoli@gmail.com>

# Copy The Nginx Configuration
COPY ./default.conf /etc/nginx/conf.d/default.conf
